version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: bd_land_postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: land_platform
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: bd_land_n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=land_platform
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=password123
    depends_on:
      - postgres

volumes:
  pgdata:
